#ifndef _COMMANDS_H
#define _COMMANDS_H

char new_line[] = "\n";

//ADC FETCH COMMANDS
#define FETCH_ADC0 "CROSS+ADC0"
#define FETCH_ADC1 "CROSS+ADC1"
#define FETCH_ADC2 "CROSS+ADC2"
#define FETCH_ADC3 "CROSS+ADC3"
#define FETCH_ADC4 "CROSS+ADC4"
#define FETCH_ADC5 "CROSS+ADC5"
#define FETCH_ADC6 "CROSS+ADC6"
#define FETCH_ADC7 "CROSS+ADC7"



#endif //_COMMANDS_H