#ifndef _COMMANDS_H
#define _COMMANDS_H

 const char new_line= '\n';

//ADC FETCH COMMANDS
#define FETCH_ADC0 "CROSS+ADC0"
#define FETCH_ADC1 "CROSS+ADC1"
#define FETCH_ADC2 "CROSS+ADC2"
#define FETCH_ADC3 "CROSS+ADC3"
#define FETCH_ADC4 "CROSS+ADC4"
#define FETCH_ADC5 "CROSS+ADC5"
#define FETCH_ADC6 "CROSS+ADC6"
#define FETCH_ADC7 "CROSS+ADC7"

/********************************************
 * GPIO COMMANDS
 * ******************************************/
//INPUT COMMANDS
#define PINB0_INPUT "CROSS+INPUT_B0"
#define PINB1_INPUT "CROSS+INPUT_B1"
#define PINB2_INPUT "CROSS+INPUT_B2"
#define PINB3_INPUT "CROSS+INPUT_B3"
#define PINB4_INPUT "CROSS+INPUT_B4"
#define PINB5_INPUT "CROSS+INPUT_B5"
#define PINB6_INPUT "CROSS+INPUT_B6"
#define PINB7_INPUT "CROSS+INPUT_B7"

#define PINC0_INPUT "CROSS+INPUT_C0"
#define PINC1_INPUT "CROSS+INPUT_C1"
#define PINC2_INPUT "CROSS+INPUT_C2"
#define PINC3_INPUT "CROSS+INPUT_C3"
#define PINC4_INPUT "CROSS+INPUT_C4"
#define PINC5_INPUT "CROSS+INPUT_C5"
#define PINC6_INPUT "CROSS+INPUT_C6"
#define PINC7_INPUT "CROSS+INPUT_C7"

#define PIND0_INPUT "CROSS+INPUT_D0"
#define PIND1_INPUT "CROSS+INPUT_D1"
#define PIND2_INPUT "CROSS+INPUT_D2"
#define PIND3_INPUT "CROSS+INPUT_D3"
#define PIND4_INPUT "CROSS+INPUT_D4"
#define PIND5_INPUT "CROSS+INPUT_D5"
#define PIND6_INPUT "CROSS+INPUT_D6"
#define PIND7_INPUT "CROSS+INPUT_D7"

//INPUT STATUS COMMANDS
#define PINB0_INPUT_STATUS "CROSS+INPUT_STATUS_B0"
#define PINB1_INPUT_STATUS "CROSS+INPUT_STATUS_B1"
#define PINB2_INPUT_STATUS "CROSS+INPUT_STATUS_B2"
#define PINB3_INPUT_STATUS "CROSS+INPUT_STATUS_B3"
#define PINB4_INPUT_STATUS "CROSS+INPUT_STATUS_B4"
#define PINB5_INPUT_STATUS "CROSS+INPUT_STATUS_B5"
#define PINB6_INPUT_STATUS "CROSS+INPUT_STATUS_B6"
#define PINB7_INPUT_STATUS "CROSS+INPUT_STATUS_B7"

#define PINC0_INPUT_STATUS "CROSS+INPUT_STATUS_C0"
#define PINC1_INPUT_STATUS "CROSS+INPUT_STATUS_C1"
#define PINC2_INPUT_STATUS "CROSS+INPUT_STATUS_C2"
#define PINC3_INPUT_STATUS "CROSS+INPUT_STATUS_C3"
#define PINC4_INPUT_STATUS "CROSS+INPUT_STATUS_C4"
#define PINC5_INPUT_STATUS "CROSS+INPUT_STATUS_C5"
#define PINC6_INPUT_STATUS "CROSS+INPUT_STATUS_C6"
#define PINC7_INPUT_STATUS "CROSS+INPUT_STATUS_C7"

#define PIND0_INPUT_STATUS "CROSS+INPUT_STATUS_D0"
#define PIND1_INPUT_STATUS "CROSS+INPUT_STATUS_D1"
#define PIND2_INPUT_STATUS "CROSS+INPUT_STATUS_D2"
#define PIND3_INPUT_STATUS "CROSS+INPUT_STATUS_D3"
#define PIND4_INPUT_STATUS "CROSS+INPUT_STATUS_D4"
#define PIND5_INPUT_STATUS "CROSS+INPUT_STATUS_D5"
#define PIND6_INPUT_STATUS "CROSS+INPUT_STATUS_D6"
#define PIND7_INPUT_STATUS "CROSS+INPUT_STATUS_D7"



#endif //_COMMANDS_H