name: AVR-UART-ADC

on:
  push:
    branches: [ master,development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install gcc-avr binutils avr-libc avrdude make
    - name: Compile code
      run: make hex
    
